### ISSUE TITLE
No code yet...

### ISSUE THREAD

**Issue by ghost** [vulkanprogrammingguide/examples#1]
Book has been out for nearly two months now... Every programmer knows nothing is perfect. Please just release it as is, and fix the mistakes as they're found...

**Comment by dstewart** [comment]
Second this...was expecting example code to be available when the book was released...

Been mostly borrowing examples from other developers/rolling my own code based on the text.

**Comment by tverstraete** [comment]
Yes, I agree ... I would rather have some code with know bugs in there and at least be able to relate the text book with the code than wait too long ...

**Comment by BennD** [comment]
Same here, sample code to actually experiment with what you learned would be very nice.
Btw. I think i found an error in code examples of the book, can anyone tell me where i can report those?

**Comment by klarheit** [comment]
live along and prosper...

**Comment by alibitek** [comment]
@grahamsellers Can you provide a rough time estimate when the code will be available?

**Comment by matthewjberger** [comment]
I agree as well. I've purchased the book and am very much looking forward to the code samples!

**Comment by mmetzler** [comment]
Total in agreement with this.. It would be really nice to get some code examples soon.

**Comment by VagueLobster** [comment]
I would also like the code to be uploaded since it is almost 3 months ago the book came out...

**Comment by Viictor** [comment]
where is the code!? 👎

**Comment by DiedeApers** [comment]
Code?

**Comment by grahamsellers** [comment]
Hi Guys,

Many apologies. Things have been a little hectic here. Was hoping to get this all polished up over the holiday season but things didn't go as planned. I'm crunching where I can and will get things posted ASAP.

**Comment by matthewjberger** [comment]
What is the status of this?

**Comment by jordisimon** [comment]
knock knock

**Comment by tverstraete** [comment]
who's there ;-)

**Comment by MoctezumaDev** [comment]
lol got the book today and still no code in this repo :(

**Comment by BennD** [comment]
@tverstraete apperently no one

**Comment by dstewart** [comment]
Hi all, I also purchased this book months ago and am still waiting for the samples. In the meantime however you should check out this repository: https://github.com/SaschaWillems/Vulkan. It has lots of examples you can build and run. Definitely helps when something in the book isn't clear.

**Comment by BennD** [comment]
thanks, ill take a look at that!

**Comment by jordisimon** [comment]
@grahamsellers any news regarding this issue? Nearly 2 months since your last comment... no code yet

**Comment by ghost** [comment]
Seems like Vulkan is pretty unusable if the guy who wrote the book on it can't even come up with example code ;) (I only kid)

**Comment by dstewart** [comment]
You should check out these code repositories until the example code is finally released:

https://github.com/SaschaWillems/Vulkan
https://github.com/gametechdev/IntroductionToVulkan
https://github.com/dstewart/Vulture

**Comment by szihs** [comment]
@grahamsellers Please update repo with code.

**Comment by ghost** [comment]
I guess it's time to report this book for incorrect information / false advertisement, and move on to the better resources available for Vulkan.
